### ISSUE TITLE
Support chained symlinks in OpenWrt/linux

### ISSUE THREAD

**Issue by jetibest** [thlib/go-timezone-local#11]
In OpenWrt I have a device where `/etc/localtime` is a symlink pointing to `/tmp/localtime` which consequently points to the right timezone.

Maybe you could put os.ReadLink into a loop (with a map memory to detect infinite loop). And/or (possibly at each step) check if the first letter of each continent/place is actually with an uppercase letter, which must be true for a timezone.

Current behavior is to simply return "tmp/localtime" which is incorrect.

**Comment by FObersteiner** [comment]
[filepath.EvalSymlinks](https://pkg.go.dev/path/filepath?utm_source=godoc#EvalSymlinks) seems to do the trick; see PR

**Comment by timohuovinen** [comment]
Thank you @FObersteiner
